baseURL = 'https://example.org/'
timezone = "Australia/Adelaide"
title = 'Markus Le'

[markup.highlight]
noclasses = false
style = "github"

[[module.imports]]
path = "github.com/willfaught/paige"
ignoreLogs = ["warning-goldmark-raw-html"]

[languages.en]
copyright = "© Markus Le"
languagecode = "en-us"
languagedirection = "ltr"
languagename = "English"
weight = 10

[markup.goldmark.renderer]
unsafe = true


[languages.en.params.paige.site]
description = "The best way to predict the future is to invent it"

[params.paige.pages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_next = true
disable_prev = true
disable_reading_time = true
disable_series = true
disable_toc = true
disable_word_count = true

[paige.pages.base_schema]
isAccessibleForFree = true
isFamilyFriendly = true

[params.paige.site]
disable_breadcrumbs = true
disable_credit = true

[params.paige.subpages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_reading_time = true
disable_series = true
disable_summary = true
disable_word_count = true

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[menu]

  [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = 10

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/project/"
    weight     = 20

  [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "/resume/"
    weight     = 30

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = 40
